from .sortingcomparison import SortingComparison, MappedSortingExtractor, compute_performance, confusion_matrix
from .multisortingcomparison import MultiSortingComparison
from .gathersortingcomparison import gather_sorting_comparison