from .sortingcomparison import SortingComparison, MappedSortingExtractor
from .multisortingcomparison import MultiSortingComparison
from .gathersortingcomparison import gather_sorting_comparison
from .comparisontools import do_matching, do_score_labels, do_counting, do_confusion_matrix, compare_spike_trains

