from .comparisontools import do_matching, do_score_labels,  do_confusion_matrix, compare_spike_trains
from .sortingcomparison import compare_two_sorters
from .groundtruthcomparison import compare_sorter_to_ground_truth
from .multisortingcomparison import compare_multiple_sorters
from .groundtruthstudy import setup_comparison_study, run_study_sorters, aggregate_sorting_comparison, aggregate_performances_table


