# Sample configuration file, for a complete reference see
# examples/config_sample_complete.yaml

# root_folder, recordings, geometry, dtype, sampling_rate, n_channels, spatial_radius, spike_size_ms, filter
# data/, neuropixel.bin, neuropixel_channels.npy, int16, 30000, 10, 70, 1, True

data:
  root_folder: {}
  recordings: {}
  geometry: {}

resources:
  max_memory: 1000000000

recordings:
  dtype: {}
  sampling_rate: {}
  n_channels: {}
  spatial_radius: {}
  spike_size_ms: {}

preprocess:
  filter: {}
  templates_partial_data: 1
  whiten_batchwise: False

spikes:
  detection: threshold
  temporal_features: 3 

deconvolution:
  rank: 3
  threshold: 4
  lam: 20

neural_network_detector:
  filename: detect_nn1.ckpt
  threshold_spike: 0.5

neural_network_triage:
  filename: triage_nn1.ckpt
  threshold_collision: 0.9

neural_network_autoencoder:
  filename: ae_nn1.ckpt
